# -*- coding: utf-8 -*-
"""generate_fleet_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJBuFF6GaEmkC2C3xHtHliOxQuUionWr
"""

import uuid
import random
from datetime import datetime, timedelta

# Configuration
NUM_VEHICLES = 50
NUM_RIDES = 500
START_DATE = datetime(2026, 5, 10, 6, 0, 0)

ZONES = ['Koramangala', 'Indiranagar', 'Whitefield', 'Electronic_City', 'HSR_Layout', 'Malleswaram', 'Jayanagar', 'Marathahalli']
MODELS = ['Maruti Dzire', 'Toyota Innova', 'Hyundai i20', 'Honda City', 'Tata Nexon', 'Mahindra XUV700', 'Kia Seltos']
AMENITIES_POOL = ['AC', 'WiFi', 'Premium_Audio', 'Dashcam', 'SUV', 'Sedan', 'Hatchback', 'Top_Rated', 'Electric']

FIRST_NAMES = ['Aarav', 'Vihaan', 'Aditya', 'Sai', 'Arjun', 'Siddharth', 'Rohan', 'Rahul', 'Amit', 'Rajesh', 'Suresh', 'Vikram', 'Manoj', 'Karthik', 'Pooja', 'Neha', 'Priya']
LAST_NAMES = ['Kumar', 'Singh', 'Patel', 'Sharma', 'Tiwari', 'Reddy', 'Rao', 'Gowda', 'Iyer', 'Menon', 'D''Souza'] # D'Souza tests the apostrophe escape!

def escape_string(text):
    """Cassandra requires single quotes to be escaped with two single quotes."""
    return text.replace("'", "''")

def generate_cql():
    with open('massive_fleet_dataset.cql', 'w') as f:
        f.write("-- ===========================================================================\n")
        f.write("-- RAPIDRIDE TELEMETRY - MASSIVE DATASET (50 Vehicles, 500 Rides)\n")
        f.write("-- ===========================================================================\n\n")

        # 1. Schema setup
        f.write("CREATE KEYSPACE IF NOT EXISTS FleetDB WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};\n")
        f.write("USE FleetDB;\n\n")

        schema = """
CREATE TABLE IF NOT EXISTS Vehicles (
    vehicle_id UUID PRIMARY KEY, driver_name TEXT, car_model TEXT, amenities LIST<TEXT>
);
CREATE TABLE IF NOT EXISTS Completed_Rides (
    zone_id TEXT, ride_time TIMESTAMP, ride_id UUID, vehicle_id UUID, distance_km DECIMAL, fare_amount DECIMAL,
    PRIMARY KEY (zone_id, ride_time, ride_id)
) WITH CLUSTERING ORDER BY (ride_time DESC);
CREATE TABLE IF NOT EXISTS Driver_Stats (
    vehicle_id UUID PRIMARY KEY, total_rides COUNTER
);
CREATE TABLE IF NOT EXISTS Surge_Pricing (
    zone_id TEXT PRIMARY KEY, surge_multiplier DECIMAL, active_reason TEXT
);
CREATE TABLE IF NOT EXISTS Archived_Rides (
    zone_id TEXT, ride_time TIMESTAMP, ride_id UUID, vehicle_id UUID, distance_km DECIMAL, fare_amount DECIMAL,
    PRIMARY KEY (zone_id, ride_time, ride_id)
);
"""
        f.write(schema + "\n")

        # 2. Generate Vehicles
        print(f"Generating {NUM_VEHICLES} vehicles...")
        f.write("-- --- VEHICLES ---\n")
        vehicles = []
        for _ in range(NUM_VEHICLES):
            v_id = str(uuid.uuid4())
            vehicles.append(v_id)
            name = f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}"
            model = random.choice(MODELS)

            # Pick 2 to 4 random amenities
            car_amenities = random.sample(AMENITIES_POOL, random.randint(2, 4))
            amenities_str = "['" + "', '".join(car_amenities) + "']"

            f.write(f"INSERT INTO Vehicles (vehicle_id, driver_name, car_model, amenities) VALUES ({v_id}, '{escape_string(name)}', '{model}', {amenities_str});\n")

        # 3. Generate Rides & Track Driver Stats
        print(f"Generating {NUM_RIDES} rides...")
        f.write("\n-- --- COMPLETED RIDES ---\n")
        driver_ride_counts = {v: 0 for v in vehicles}

        current_time = START_DATE
        for _ in range(NUM_RIDES):
            # Advance time by a random amount between 1 and 20 minutes
            current_time += timedelta(minutes=random.randint(1, 20), seconds=random.randint(0, 59))

            zone = random.choice(ZONES)
            v_id = random.choice(vehicles)
            distance = round(random.uniform(1.5, 25.0), 1)

            # Base fare 50 + 15 per km, plus a small random variance
            fare = round(50 + (15 * distance) + random.uniform(0, 20), 2)

            # Notice: No UNLOGGED BATCH here. Individual async inserts prevent the Cassandra warnings!
            time_str = current_time.strftime('%Y-%m-%dT%H:%M:%S.000+0000')
            f.write(f"INSERT INTO Completed_Rides (zone_id, ride_time, ride_id, vehicle_id, distance_km, fare_amount) VALUES ('{zone}', '{time_str}', now(), {v_id}, {distance}, {fare});\n")

            driver_ride_counts[v_id] += 1

        # 4. Generate Driver Stats (Counters)
        f.write("\n-- --- DRIVER STATS (COUNTERS) ---\n")
        for v_id, count in driver_ride_counts.items():
            if count > 0:
                # We can update the counter with the total directly for dataset seeding
                f.write(f"UPDATE Driver_Stats SET total_rides = total_rides + {count} WHERE vehicle_id = {v_id};\n")

        # 5. Generate Surge Pricing (TTL)
        f.write("\n-- --- SURGE PRICING (TTL) ---\n")
        f.write("INSERT INTO Surge_Pricing (zone_id, surge_multiplier, active_reason) VALUES ('Koramangala', 1.8, 'Heavy Rain') USING TTL 3600;\n")
        f.write("INSERT INTO Surge_Pricing (zone_id, surge_multiplier, active_reason) VALUES ('Electronic_City', 2.1, 'Office Rush Hour') USING TTL 1800;\n")
        f.write("INSERT INTO Surge_Pricing (zone_id, surge_multiplier, active_reason) VALUES ('Indiranagar', 1.5, 'Concert Event') USING TTL 7200;\n")
        f.write("INSERT INTO Surge_Pricing (zone_id, surge_multiplier, active_reason) VALUES ('Whitefield', 1.3, 'Traffic Snarl') USING TTL 1200;\n")

        print("Done! File 'massive_fleet_dataset.cql' generated successfully.")

if __name__ == "__main__":
    generate_cql()